# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecc7ec4ce767d3ce0302d8c416ba7aa27c5c012c475b44bf0b68b4428156bf327b21c840ed6ccd659e41232d37c11cab954a4fdf8d00e03a164753d230adb881

test:
  secret_key_base: 4008d1f6a80e27c4fb994538431f0b04e48e77bc3302e27ff0a4bcb08327a60df816be7ef03fbbb4a8f8d88b22deaa4cf80f2f2b5796183ce55ebb3ee3d50077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
